import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from 'next-auth'
import SessionProvider from "./components/sessionProvider";
import { Providers } from "./components/nextuiProvider";
import "./globals.css";


import NavBar from "./components/navigator/navBar";
import Footer from "./components/navigator/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wongnok recipes",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SessionProvider session={session}>
            <NavBar />
              {children}
            <Footer />
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
